### ISSUE TITLE
Consider Githooks

### ISSUE THREAD

**Issue by gabyx** [swellaby/captain-githook#75]
Hi Devs,

Consider contributing to https://github.com/gabyx/githooks. Disclaimer it was orginally not written by me but ported and rewritten to Go by me.
Contribution is highly welcome as it could get more aswesome etc.

BR

**Comment by calebcartwright** [comment]
Thanks for sharing! There's a few different philosophies and approaches to facilitating client side hooks and each has their merits. We're pretty content with the approach we've taken here and the fact that it meets our goals in a simple way; if it happens to be useful for others too then that's great!

We don't really have any major development plans pending, but will continue to maintain this project unless and until an alternative comes along that's a better fit for our specific needs. Your project looks really interesting (and powerful!) but it doesn't fit that criteria of being a better alternative for our specific goals and needs. I definitely wish you the best of luck with your project but we don't really have the bandwidth to contribute to alternative projects which are geared towards the same capability set, so I'm going to close this.
